export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const CREAR_USUARIOS = "CREAR_USUARIOS";
export const MODIFICAR_USUARIOS = "MODIFICAR_USUARIOS";
export const ELIMINAR_USUARIOS = "ELIMINAR_USUARIOS";

export const OBTENER_TICKETS = "OBTENER_TICKETS";
export const CREAR_TICKETS = "CREAR_TICKETS";
export const MODIFICAR_TICKETS = "MODIFICAR_TICKETS";
export const ELIMINAR_TICKETS = "ELIMINAR_TICKETS";

export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
export const CREAR_CLIENTES = "CREAR_CLIENTES";
export const MODIFICAR_CLIENTES = "MODIFICAR_CLIENTES";
export const ELIMINAR_CLIENTES = "ELIMINAR_CLIENTES";

export const OBTENER_ROLES = "OBTENER_ROLES";
export const OBTENER_SERVICIOS = "OBTENER_SERVICIOS";
export const OBTENER_ESTADO = "OBTENER_ESTADO";
export const OBTENER_PRIORIDAD = "OBTENER_PRIORIDAD";

export const VERIFICAR_LOGUEO = "VERIFICAR_LOGUEO";
export const USUARIO_LOGUEADO = "USUARIO_LOGUEADO";
export const USUARIO_DESLOGUEADO = "USUARIO_DESLOGUEADO";