export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const CREAR_USUARIOS = "CREAR_USUARIOS";
export const MODIFICAR_USUARIOS = "MODIFICAR_USUARIOS";
export const ELIMINAR_USUARIOS = "ELIMINAR_USUARIOS";

export const OBTENER_TICKETS = "OBTENER_TICKETS";
export const CREAR_TICKETS = "CREAR_TICKETS";
export const MODIFICAR_TICKETS = "MODIFICAR_TICKETS";
export const ELIMINAR_TICKETS = "ELIMINAR_TICKETS";